"""Recover candidate functions for this exact revision with spimdisasm.

This is an analysis artifact, not a claim that every candidate is correct. Data,
RSP instructions and unresolved boundaries are explicitly recorded for review.
"""
import hashlib
import json
from pathlib import Path
import spimdisasm as spim

ROOT = Path(__file__).resolve().parents[1]
(ROOT/'reports').mkdir(exist_ok=True)
(ROOT/'build').mkdir(exist_ok=True)


def main():
    b = (ROOT/'roms/rogue_squadron.us.rev1.z64').read_bytes()
    layout = json.loads((ROOT/'config/segments.json').read_text())
    if hashlib.sha256(b).hexdigest() != layout['rom_sha256']:
        raise ValueError('ROM mismatch')
    spim.common.GlobalConfig.COMPILER = spim.common.Compiler.SN64
    spim.common.GlobalConfig.QUIET = True
    ctx = spim.common.Context()
    ctx.changeGlobalSegmentRanges(0x1000, 0x96ce0, 0x80000400, 0x80145d90)
    reviewed = json.loads((ROOT/'config/reviewed-functions.json').read_text())
    discovered_path=ROOT/'config/discovered-functions.json'
    if discovered_path.exists():
        for name,entries in json.loads(discovered_path.read_text()).items():
            explicit={int(e['vram'],16) for e in reviewed.get(name,[])}
            reviewed.setdefault(name,[]).extend(e for e in entries if int(e['vram'],16) not in explicit)
    data_ranges = json.loads((ROOT/'config/reviewed-data.json').read_text())
    sections = []
    for spec in layout['sections']:
        start, vram, size = (int(spec[k], 16) for k in ('rom', 'vram', 'size'))
        overlay = spec['name'] if spec['name'] != 'main' else None
        if overlay:
            symbols = ctx.addOverlaySegment(overlay, start, start+size, vram, vram+size+int(spec['bss_size'],16))
        else:
            symbols = ctx.globalSegment
        for entry in reviewed.get(spec['name'], []):
            addr = int(entry['vram'],16)
            symbol = symbols.addFunction(addr, isAutogenerated=False, vromAddress=start+addr-vram)
            symbol.isUserDeclared = True
            if 'size' in entry:
                symbol.userDeclaredSize = int(entry['size'],16)
        analysis_start = int(spec.get('analysis_start', spec['rom']), 16)
        analysis_end = int(spec.get('analysis_end', hex(start+size)), 16)
        sec = spim.mips.sections.SectionText(ctx, analysis_start, analysis_end, vram+analysis_start-start,
                                            spec['name'], b, start, overlay)
        sections.append((spec, sec))
    # Seed direct-call targets from every overlay before splitting main code.
    # Otherwise a main routine referenced only by mission code can be swallowed
    # by its preceding function. This invokes the same prepass used by analyze().
    for _, sec in sections:
        sec._findCalls(sec.wordListToInstructions(sec.words, sec.vram, sec.instrCat))
    for _, sec in sections:
        sec.analyze()
    for spec,sec in sections:
        start,vram=(int(spec[k],16) for k in ('rom','vram'))
        for entry in reviewed.get(spec['name'],[]):
            if not entry.get('separate_text'):continue
            address=int(entry['vram'],16);offset=start+address-vram;size=int(entry['size'],16)
            fragment=spim.mips.sections.SectionText(ctx,offset,offset+size,address,spec['name'],b,start,
                spec['name'] if spec['name']!='main' else None)
            fragment.analyze();sec.symbolList.extend(fragment.symbolList)
    result = []
    toml = []
    cache_patches = []
    host_replacements = []
    pc_captures = []
    for spec, sec in sections:
        start, vram, size = (int(spec[k], 16) for k in ('rom', 'vram', 'size'))
        toml += ['[[section]]', f'name = ".{spec["name"]}"', f'rom = {start:#x}', f'vram = {vram:#x}', f'size = {size:#x}', 'functions = [']
        candidates = []
        if spec['name'] == 'main':
            toml += ['  { name = "main_80000400", vram = 0x80000400, size = 0xc },',
                     '  { name = "main_8000040C", vram = 0x8000040c, size = 0x30 },']
            cache_patches.append({'function': 'main_8000040C', 'vram': 0x8000041c, 'original': 0xbd0d0000})
        for f in sec.symbolList:
            if not hasattr(f, 'instructions'):
                continue
            fn = f'{spec["name"]}_{f.vram:08X}'
            issues = []
            known_data = any(r['section'] == spec['name'] and int(r['vram'],16) <= f.vram
                             and f.vram + f.nInstr*4 <= int(r['vram'],16) + int(r['size'],16)
                             for r in data_ranges)
            if known_data:
                issues.append('Reviewed embedded data, not code')
            if f.hasUnimplementedIntrs:
                issues.append('Unknown instructions or embedded data')
            if f.isLikelyHandwritten:
                issues.append('Handwritten code or hardware access requires review')
            item = {'name': fn, 'vram': f.vram, 'rom': f.vromStart, 'size': f.nInstr*4,
                    'unknown_instructions': f.hasUnimplementedIntrs,
                    'known_data': known_data,
                    'handwritten': f.isLikelyHandwritten, 'review': issues,
                    'sha256': hashlib.sha256(b[f.vromStart:f.vromStart+f.nInstr*4]).hexdigest()}
            candidates.append(item)
            if not f.hasUnimplementedIntrs and not known_data:
                toml.append(f'  {{ name = "{fn}", vram = {f.vram:#x}, size = {f.nInstr*4:#x} }},')
                privileged = []
                for offset, instr in enumerate(f.instructions):
                    word = int.from_bytes(b[f.vromStart+offset*4:f.vromStart+offset*4+4], 'big')
                    if instr.getOpcodeName() == 'cache':
                        cache_patches.append({'function': fn, 'vram': f.vram + offset*4,
                                              'original': word})
                    op = instr.getOpcodeName()
                    if word & 0xffff0000 == 0x04100000:
                        # BLTZAL $zero never branches but writes PC+8 to $ra.
                        # This game uses it to locate inline audio tables.
                        # N64Recomp's C-call convention otherwise loses that write.
                        pos = f.vromStart + offset*4
                        if b[pos+4:pos+8] != b'\0'*4:
                            raise ValueError('PC capture has a non-NOP delay slot; manual adaptation required')
                        pc_captures.append({'function': fn, 'vram': f.vram+offset*4,
                                            'return_address': f.vram+offset*4+8})
                    if (op in ('mfc0', 'mtc0') and (word >> 11) & 31 != 12) or op in ('eret', 'tlbp', 'tlbr', 'tlbwi', 'tlbwr'):
                        privileged.append({'vram': f.vram+offset*4, 'instruction': instr.disassemble()})
                if privileged:
                    host_replacements.append({'function': fn, 'instructions': privileged,
                                              'status': 'Unimplemented; kernel or hardware service requires native replacement and identification'})
        toml.append(']\n')
        result.append({'section': spec['name'], 'candidates': candidates})
    (ROOT/'reports/code-analysis.json').write_text(json.dumps({'rom_sha256': layout['rom_sha256'], 'sections': result}, indent=2)+'\n')
    (ROOT/'build/candidate-symbols.toml').write_text('\n'.join(toml))
    config = ['[input]', 'symbols_file_path = "candidate-symbols.toml"',
              'rom_file_path = "../roms/rogue_squadron.us.rev1.z64"',
              'output_func_path = "candidate-generated"', 'functions_per_output_file = 1',
              'uses_mips3_float_mode = false', 'use_lookup_for_all_function_calls = true', '']
    config += ['[patches]', 'ignored = ' + json.dumps([r['function'] for r in host_replacements]), '']
    config += ['[[patches.hook]]', 'func = "main_80001F1C"', 'before_vram = 0x80001f80',
               'text = "pause_self(rdram);"', '']
    for poll_address in (0x80081098,0x80081124):
        config += ['[[patches.hook]]','func = "main_8008106C"',f'before_vram = {poll_address:#x}',
                   'text = "rs_cooperative_poll(rdram);"','']
    config += ['[[patches.hook]]','func = "main_8008DAE0"','before_vram = 0x8008db80',
               'text = "if (ctx->r2 == 0) rs_cooperative_poll(rdram);"','']
    # Stream shutdown spins until the audio worker clears the channel state.
    # The original VI interrupt schedules that worker; deliver events here.
    config += ['[[patches.hook]]','func = "main_8008FC94"','before_vram = 0x8008fcbc',
               'text = "rs_cooperative_poll(rdram);"','']
    # Handwritten matrix conversion saves the caller's $ra in $t9 and returns
    # through it after three JALs. Under the native C-call convention this is a
    # return to the C caller, not an indirect call into the address lookup table.
    config += ['[[patches.instruction]]','func = "main_800137D0"',
               'vram = 0x800138a8','value = 0x03e00008','']
    for patch in cache_patches:
        config += ['[[patches.instruction]]', f'func = "{patch["function"]}"',
                   f'vram = {patch["vram"]:#x}', 'value = 0', '']
    for capture in pc_captures:
        ra = capture['return_address']
        for delta, value in [(0, 0x3c1f0000 | (ra >> 16)), (4, 0x37ff0000 | (ra & 0xffff))]:
            config += ['[[patches.instruction]]', f'func = "{capture["function"]}"',
                       f'vram = {capture["vram"]+delta:#x}', f'value = {value:#x}', '']
    (ROOT/'build/candidate.toml').write_text('\n'.join(config))
    (ROOT/'reports/cache-adaptations.json').write_text(json.dumps({
        'reason': 'N64 cache maintenance is not needed for coherent host buffers; executable functions are statically compiled, with overlay dispatch supplied separately.',
        'patches': cache_patches}, indent=2)+'\n')
    (ROOT/'reports/required-host-services.json').write_text(json.dumps(host_replacements, indent=2)+'\n')
    (ROOT/'reports/pc-capture-adaptations.json').write_text(json.dumps(pc_captures, indent=2)+'\n')
    for s in result:
        fs=s['candidates']
        print(s['section'], {'candidates': len(fs), 'unknown_or_data': sum(f['unknown_instructions'] for f in fs),
                             'handwritten_or_hardware': sum(f['handwritten'] for f in fs)})


if __name__ == '__main__':
    main()
